# 开发环境配置
server:
  # 服务端口
  port: 8234
  servlet:
    # 项目contextPath
    context-path: /sofb-manager
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  application:
    name: sofb-manager
  redis:
    config:
      clusterNodes: 10.152.200.251:6378
      maxIdle: 100
      maxTotal: 500
      minIdle: 5
      maxWaitMillis: 20000
      password: 123456
      connectionTimeout: 6000
      maxAttempts: 10
      soTimeout: 6000

logging.config= classpath: logback.xml

eureka:
  client:
    service-url:
      defaultZone: http://10.152.200.251:9000/eureka/eureka

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100

shiro:
  config:
    anon-url:
    login-url: /login
    logout-url: /logout
    success-url: /index
